CREATE DATABASE testdb;

CREATE ROLE test WITH LOGIN PASSWORD 'test';

GRANT ALL PRIVILEGES ON DATABASE testdb to test;

GRANT ALL ON ALL TABLES IN SCHEMA public TO test;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO test;